description: Sinatra (master branch)
base-diff-url: https://github.com/sinatra/sinatra/commit/
write-json-diffs: false
testable-file-suffixes: 
- .rb
redactions: 
- "@95fbf360-2702-46e8-84d8-6de9ca90a270"
aliases:
  - Adam Wiggins;adam@heroku.com
  - Alexander Klink;alech
  - Andrey Samsonov;samsonov 
  - Ben Bleything;bleything
  - Blake Mizerany;izerany
  - Chris Schneider;christopher-s
  - Chris Wanstrath;chris@ozmm.org;
  - Dylan Egan;dylanegan;
  - Erik Kastner;kastner
  - Gabriel Andretta;ohhgabriel
  - Homer Simpson;homer
  - Ian Dees;undees 
  - Igal Koshevoy;igal
  - jammur;jammur
  - Jeremy Evans;jeremyevans
  - Jimmy Schementi;jschementi
  - Jon Crosby;rosby
  - Joshua Peek;joshpeek
  - Karel Minarik;karmi
  - kematzy;kematzy
  - Konstantin Haase;konstantin,haase
  - Luciano Sousa;uciano
  - Markus Prinz;prinz
  - Ryan Tomayko;rtomayko
  - Simon Rozet;rozet
  - t_huehn;t_huehn
  - Vasily Polovnyov;vast,polovnyov,vazilla
  - Trevor Bramble;trevorbramble,tbramble
  - Will Bailey;will.bailey
  - Anurag Priyam;anurag08priyam
  - ymmtmsys;m2yamamoto
  - Chris Heald;cheald
  - Katrina Owen;atrina.owen
  - Adrian Paca;altpacala
  - Aleksander Dabrowski;dabrowski
  - Attila Olah;attilaolah
  - bjoerge;bjoerge
  - magallania;magallania
  - Dario;dario
  - Dyego Costa;dyego
  - Eric Marden;eric.marden,eric@xentek
  - Florian Hanke;florian.hanke
  - James Tucker;jftucker,raggi
  - Jon Rowe;jonrowe
  - Michael Klishin;michael@defprotocol.org,michaelklishin
  - Nicolas Sanguinetti;nicolassanguinetti,godfoca
  - Nikita Bulai;bulaj.nikita,nbulaj
  - Orange Tsai;orange
  - Peter Suschlik;suschlik
  - Seiichi Yonezawa;nzwsch
  - Shim Tw;marocchino,twshim
  - Sylvain Desve;sylvain.desve
  - Tobias Buehlmann;buehlmann
  - Vasiliy Yakliushin;vyaklushin@;vasiliy.yaklushin
  - Wu Jiang;masterwujiang@
  - Yegor Timoschenko;yegortimoschenko
  - Zachary Scott;zzak.iozachary.s.scott
  - burningTyger;b6tyger@,m8r-0478r31
  - namusyaka;kunpei,namusyaka
