description: Sinatra (master branch)
base-diff-url: https://github.com/sinatra/sinatra/commit/
write-json-diffs: false
testable-file-suffixes: 
- .rb
redactions: 
- "@95fbf360-2702-46e8-84d8-6de9ca90a270"
aliases:
  - Gabriel Andretta;ohhgabriel
  - Konstantin Haase;konstantin,haase
  - Vasily Polovnyov;vast,polovnyov,vazilla
  - Trevor Bramble;trevorbramble,tbramble
  - Aleksander Dabrowski;dabrowski
  - Eric Marden;eric.marden,eric@xentek
  - James Tucker;jftucker,raggi
  - Michael Klishin;michael@defprotocol.org,michaelklishin
  - Nicolas Sanguinetti;nicolassanguinetti,godfoca
  - Nikita Bulai;bulaj.nikita,nbulaj
  - Vasiliy Yakliushin;vyaklushin@,vasiliy.yaklushin
  - burningTyger;b6tyger,m8r-0478r31
